/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diary;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import Diary.database.Database;

/**
 *
 * @author Shafiq
 */
public class LoginWindow extends javax.swing.JFrame {

	/**
	 * Creates new form LoginWindow
	 */

	public LoginWindow() {
		new Database();
		initComponents();
		setLocationRelativeTo(null);
		setTitle("Login");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		usernameText = new javax.swing.JTextField();
		passwordText = new javax.swing.JPasswordField();
		sineup = new javax.swing.JButton();
		login = new javax.swing.JButton();
		errorLael = new javax.swing.JLabel();

		sineup.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				if (usernameText.getText() != ""
						&& passwordText.getText() != "")
					try {
						Database.createUser(usernameText.getText(),
								passwordText.getText());
						dispose();
						MainFrame.username = usernameText.getText();
						MainFrame.InitApp();
					} catch (Exception e) {
						JOptionPane
								.showMessageDialog(null,
										"Error!!!! User already Exists or Server not found. ");
					}

			}
		});
		login.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent ex) {
				if (usernameText.getText() != ""
						&& passwordText.getText() != "")
					try {
						if (Database.checkUser(usernameText.getText(),
								passwordText.getText())) {
							dispose();
							MainFrame.username = usernameText.getText();
							MainFrame.InitApp();
						} else {
							JOptionPane.showMessageDialog(null,
									"Username or Password does not match.");
						}
					} catch (Exception e) {
						JOptionPane.showMessageDialog(null,
								"Error!!!! User already Exists or Server not found. "
										+ e.getMessage());
					}

			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel1.setText("User name:  ");

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel2.setText("Password");

		usernameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

		passwordText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

		sineup.setText("Sign Up");

		login.setText("Login");

		errorLael.setBackground(new java.awt.Color(255, 0, 51));
		errorLael.setForeground(new java.awt.Color(255, 0, 0));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(34, 34,
																		34)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						86,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						86,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(40, 40,
																		40)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										sineup)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										29,
																										Short.MAX_VALUE)
																								.addComponent(
																										login))
																				.addComponent(
																						usernameText)
																				.addComponent(
																						passwordText)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(42, 42,
																		42)
																.addComponent(
																		errorLael,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		284,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(64, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(51, 51, 51)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jLabel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														26,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														usernameText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jLabel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														26,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														passwordText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(login)
												.addComponent(sineup))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										33, Short.MAX_VALUE)
								.addComponent(errorLael).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginWindow().setVisible(true);
			}
		});

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel errorLael;
	private javax.swing.JButton sineup;
	private javax.swing.JButton login;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPasswordField passwordText;
	private javax.swing.JTextField usernameText;
	// End of variables declaration//GEN-END:variables
}
